name: Update hellen-one Reference

on:
  schedule:
    - cron: '2 15 * * *' # update reference daily at 2:15 pm
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: andreika-git/hellen-one/.github/workflows/custom-board-update-hellen-one-reference.yaml@master
    permissions:
      contents: write
